spring.application.name=redisconnect
# Ativa a integração do Spring com o Docker Compose
spring.docker.compose.enabled=true
# Indica o caminho exato do arquivo docker-compose
spring.docker.compose.file=./docker-compose.yaml
# Define o que fazer quando a aplicação for parada (padrão é stop)
spring.docker.compose.lifecycle-management=start-and-stop