# Nome da aplicação
spring.application.name=redisconnect

# --- Configurações de Redis (Flexíveis para Local e Produção) ---
# O Spring dá prioridade para a variável de ambiente.
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# --- Configurações de Docker Compose (Apenas para Desenvolvimento) ---
# Ativa a integração do Spring com o Docker Compose local
spring.docker.compose.enabled=true
# Indica o caminho exato do arquivo docker-compose
spring.docker.compose.file=./docker-compose.yaml
# Define o que fazer quando a aplicação for parada
spring.docker.compose.lifecycle-management=start-and-stop